### ISSUE TITLE
synthesizing image

### ISSUE THREAD

**Issue by sdx2199** [Shreeyak/cleargrasp#13]
Hello, I would like to consult the method of synthesizing image, especially the method of synthesizing depth map.

**Comment by Shreeyak** [comment]
The images were rendered using Blender. Unfortunately, that code is not available. However, we will release similar rendering code in a few months for our follow-up project.

**Comment by kontramind** [comment]
Hi, any chances that the rendering code you mention above has been released?

**Comment by MaekTec** [comment]
Hi,
is there any update on this? Did you already released a similar rendering code?
Thanks for your answer!

**Comment by Shreeyak** [comment]
Hey, thank you for your interest! Unfortunately, I was on a break. The rendering code is still in progress. 
However, a recent work called SuperCaustics was recently released which allows rendering images with better caustics. Check it out here: https://github.com/MMehdiMousavi/SuperCaustics
