### ISSUE TITLE
Is pytorch 1.1.0 worked?

### ISSUE THREAD

**Issue by Mr-Bang** [Shreeyak/cleargrasp#18]
I installed the cuda 9.0 in the tutorial, but it seems that the cuda 9.0 only support pytorch 1.1.0. Is that ok? By the way, my gpu is RTX 2080. Waiting for your answer!

**Comment by Shreeyak** [comment]
It should work with v1.1.0. Do try to run and see if you get any errors.
If required, you can always build from source.

**Comment by Shreeyak** [comment]
@Mr-Bang BTW, this code should run with later versions of CUDA/Pytorch.
