### ISSUE TITLE
Working on Realsense L515

### ISSUE THREAD

**Issue by Mr-Bang** [Shreeyak/cleargrasp#19]
Hey! Thanks for your code, it really helps. I am wondering if this code can work on the Intel Realsense L515 device. It seems something wrong with this device.

**Comment by Shreeyak** [comment]
It should. I beleive the intel realsense api can read from the new device as well. You would have to upgrade to a newer version however, and there might be some api changes in the newer version.
Once you can get the depth image, rest of the code is the same, it will work.

**Comment by Shreeyak** [comment]
@Mr-Bang Were you able to resolve this?
