### ISSUE TITLE
Pre-trained Models

### ISSUE THREAD

**Issue by MMehdiMousavi** [Shreeyak/cleargrasp#20]
Hi, 
I'm doing training from scratch, and I do not have the resources to pre-train on MP and SN. Is it possible you could share those pre-trained models (without training on the synthetic data, just MP and SN.)

Thanks!

**Comment by Shreeyak** [comment]
At this time, I'm tied up with other work. But I might be able to next week. 
Mainly, I don't have those datasets, and they're huge. So I won't be able to commit, but will let you know.
