### ISSUE TITLE
How many epochs to train it from scratch?

### ISSUE THREAD

**Issue by ahmedwael19** [Shreeyak/cleargrasp#22]
I'm currently working on a research project that makes use of your awesome paper/code.

I'm just curious to know how many epochs it took you to train the 3 networks from scratch? 

I mean the results you reported in the paper after how many epochs as it's not clear.

Thanks

**Comment by MMehdiMousavi** [comment]
I think they mentioned something like 500 epochs on 196 batch size. not sure though. I doubt any single researcher can achieve such results without the 8 Tesla v100s that these folks used. (hint: check out supercaustics from my repo.)

**Comment by Shreeyak** [comment]
I don't have those statistics available at this point. I do remember surface normals taking 3 days to train from scratch on a 4x v100 machine. When I took checkpoint pretrained on Matterport3D, then the training was much faster.

I trained the models until the graphs saturated. I'll be sure to mention this detail in my future works.

**Comment by Shreeyak** [comment]
@MMehdiMousavi SuperCaustics looks amazing. Nice work!
