### ISSUE TITLE
Question on depth (both for training and inference)

### ISSUE THREAD

**Issue by kontramind** [Shreeyak/cleargrasp#24]
Hi Shreeyak,

**Q1**: Does the pipeline expect rectified depth images (depth values wrt camera plane) during **inference**?
**Q2**: Does the pipeline expect rectified depth images (depth values wrt camera plane) during **training**?
**Q3**: Are Realsense cameras then outputting already rectified depth or additional step(s) need to be done?

Many thanks

**Comment by Shreeyak** [comment]
Hi! Apologies for the delayed response. I've been on a break.

A1: Yes. All depth values are from the camera plane. Not from camera center.
A2: Yes.
A3: The realsense cameras do output depth from camera plane. It's the same for other RGBD cameras I've worked with.
