### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by CodeKingWang** [Shreeyak/cleargrasp#29]
I have trained surface normal network, but there are some warnings,as below:
![image](https://user-images.githubusercontent.com/38208467/145766475-bce0b591-0211-49e6-9c62-3e70fdebbaa9.png)

**Comment by Shreeyak** [comment]
I'm assuming this is the early stages of training? The error is lovely because the predictions are all bad.
Visualize the predicted normals to check.

Of this is early stages, training for more time should resolve the issue.
