### ISSUE TITLE
Installation Question (Python, CUDA Version)

### ISSUE THREAD

**Issue by trevor-taeyeop** [Shreeyak/cleargrasp#3]
Hi, Shreeyak. 
`This code is tested with Ubuntu 16.04, Python3 and Pytorch 1.1.`
Could you explain detailed python3 version (ex. 3.6.7)??
Also, Which CUDA version did you used for the test??

**Comment by Shreeyak** [comment]
Hey @trevor-taeyeop , I've updated the readme with this information.
I used Python 3.6.8, Pytorch 1.3 and CUDA 9.0.

**Comment by MMehdiMousavi** [comment]
Is it tested on windows? or do I have to run it on Linux?

**Comment by Shreeyak** [comment]
This repo has been tested only on Ubuntu. Since it's PyTorch, you should be able to get it to run on windows, but I can't help with that.
