### ISSUE TITLE
Everything is working, but openexrpython is a kind of old?

### ISSUE THREAD

**Issue by jiapei-nexera** [Shreeyak/cleargrasp#35]
[https://github.com/AcademySoftwareFoundation/openexr](https://github.com/AcademySoftwareFoundation/openexr) now has a new lease 3.1.5 ....

**Comment by Shreeyak** [comment]
Thank you, it's good to know openexrpython is getting updates.
This project however was released a long time ago and the versions reflect
those used at the time.
Updating versions of all the libraries is likely to introduce some
conflicts.
