### ISSUE TITLE
Can any of you explain this a little bit to me, about the meaning of every single cell in the grid image ??

### ISSUE THREAD

**Issue by jiapei-nexera** [Shreeyak/cleargrasp#36]
Hi, I'm using a D415, with 

RGB size: 640*480
Depth size: 720*1280

and depth_completion() return image/depth size (**depthcomplete.input_image** and **depthcomplete.input_depth**) of 144*256 ....

Can't even see very clearly....

**Comment by jiapei100** [comment]
Got it... there is an example in librealsense **ethernet_client_server** ...

**Comment by jiapei-nexera** [comment]
Can any of you explain this a little bit to me, about the meaning of every single cell in the grid image ??

[Live Demo Picture](https://imgur.com/gallery/vR8uu9u)



```python
        grid_image1 = np.concatenate((color_img, surface_normals_rgb, outlines_rgb, occlusion_weight_rgb), 1)
        grid_image2 = np.concatenate((input_depth_mapped, output_depth_mapped, filtered_output_depth_mapped,
                                      np.zeros(color_img.shape, dtype=color_img.dtype)), 1)
        grid_image = np.concatenate((grid_image1, grid_image2), 0)
```

**Comment by Shreeyak** [comment]
@jiapei-nexera We downsample the image before feeding it to the neural network, resulting in the 144x256 image size. 

As for the code, you posted, it simply creates 4x2 grid of images: The RGB image from camera, the predicted surface normals for that image, the outlines as shown in the paper, the weight applied to the occlusion boundaries, the input depth, the cleaned output depth, and a filtered version of the output depth.

**Comment by JinraeKim** [comment]
~~@Shreeyak What is "filtered output" depth?~~
I found it [here](https://github.com/JinraeKim/cleargrasp/blob/master/api/depth_completion_api.py#L806)
