### ISSUE TITLE
Which model is trained for Model checkpoints in README?

### ISSUE THREAD

**Issue by JinraeKim** [Shreeyak/cleargrasp#38]
In `READE.md`:

> Download the data:
a) [Model Checkpoints](https://storage.googleapis.com/cleargrasp/cleargrasp-checkpoints.zip) (0.9GB) - Trained checkpoints of our 3 deeplabv3+ models.
b) [Train dataset](https://storage.googleapis.com/cleargrasp/cleargrasp-dataset-train.tar) (Optional, 72GB) - Contains the synthetic images used for training the models. No real images were used for training.
c) [Val + Test datasets](https://storage.googleapis.com/cleargrasp/cleargrasp-dataset-test-val.tar) (Optional, 1.7GB) - Contains the real and synthetic images used for validation and testing.

And I realised that in the sample config, it is specified as `drn`:

```yaml
  17 # Surface Normals Model
  18 normals:
  19   model: 'drn'  # Which model to use for inference. Possible values: ['unet', 'deeplab_resnet']
  20   pathWeightsFile: '../data/cleargrasp-checkpoints/surface_normals/checkpoint_normals.pth'  # Path to the checkpoint to be loaded
  21   inferenceHeight: 256
  22   inferenceWidth: 256
```

Is the Model checkpoints (provided in README) `drn`?
Is `drn` different from `unet` or `deeplab_resnet`?

**Comment by Shreeyak** [comment]
I believe it's the drn model. Drn is a variant of resnet containing dilated convolutions, giving it a bigger receptive field.

Here's the link to the model used: https://github.com/Shreeyak/cleargrasp/blob/master/pytorch_networks/surface_normals/modeling/backbone/drn.py
